name: Auto Commit

on:
  schedule:
    - cron: "0 0 * * *" # Chạy mỗi ngày lúc 00:00 UTC (7:00 AM giờ Việt Nam)
  workflow_dispatch: # Cho phép chạy thủ công nếu cần

jobs:
  auto-commit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Cấu hình Git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Thực hiện thay đổi
        run: |
          echo "Cập nhật lúc $(date)" >> auto-update-log.txt

      - name: Kiểm tra sự thay đổi
        run: |
          git add .
          if git diff --cached --quiet; then
            echo "Không có thay đổi nào, thoát..."
            exit 0
          fi

      - name: Commit & Push thay đổi
        run: |
          git commit -m "Auto commit: $(date)"
          git push origin main
